import {
  PedzikowImage,
  KayakImage,
  VillageMuseumImage,
  ChecinyCastleImage,
  CaveImage,
  DavinciCenterImage,
  CourtImage,
  PotteryCenterImage,
  NiemczowkaImage,
  GeoCenterImage,
  SobkowCastleImage,
  MillImage,
  ZooImage,
  GeonaturaImage,
  AnimaLiberaImage,
  PerlaWaterParkImage,
  MiningMuseumImage,
  ToyMuseumImage,
  DakarTownImage,
  PopeCarMuseumImage,
  BotanicGardenImage,
  UFOImage,
  WitchHavenImage,
  LipaManorImage,
} from 'helpers/importAllNearbyImages';

const NEARBY_DATA = [
  {
    title: 'Gród Pędzików',
    distance: '2,8km',
    image: PedzikowImage,
    link: 'https://www.grodpedzikow.pl/',
  },
  {
    title: 'Spływ kajakiem "Bastek"',
    distance: '1,9km',
    image: KayakImage,
    link: 'https://nidy.pl/',
  },
  {
    title: 'Muzeum Wsi Kieleckiej w Tokarni',
    distance: '5,4km',
    image: VillageMuseumImage,
    link: 'https://www.mwk.com.pl/',
  },
  {
    title: 'Zamek Królewski w Chęcinach',
    distance: '8,3km',
    image: ChecinyCastleImage,
    link: 'https://zamek.checiny.pl/pl/',
  },
  {
    title: 'Jaskinia Raj',
    distance: '11,9km',
    image: CaveImage,
    link: 'https://jaskiniaraj.pl/',
  },
  {
    title: 'Centrum Nauki Leonardo Da Vinci',
    distance: '6,7km',
    image: DavinciCenterImage,
    link: 'https://cndavinci.pl/',
  },
  {
    title: 'Dwór Starostów Chęcińskich',
    distance: '6,5km',
    image: CourtImage,
    link: 'https://cndavinci.pl/index.php/przyklad3/dwor-starostow-checinskich/',
  },
  {
    title: 'Park Wodny Perła',
    distance: '12,9km',
    image: PerlaWaterParkImage,
    link: 'https://perla.nowiny.com.pl/',
  },
  {
    title: 'Muzeum Samochodu Papieskiego JP2',
    distance: '29,8km',
    image: PopeCarMuseumImage,
    link: 'https://www.msjp2.pl/',
  },
  {
    title: 'Muzeum Zabawek i Zabawy',
    distance: '21,9km',
    image: ToyMuseumImage,
    link: 'https://muzeumzabawek.kielce.eu/',
  },
  {
    title: 'ZOO "Leśne zacisze"',
    distance: '16,5km',
    image: ZooImage,
    link: 'https://www.lesne-zacisze.net/',
  },
  {
    title: 'Góra Miedzianka',
    distance: '16,8km',
    image: MiningMuseumImage,
    link: 'https://www.checiny.pl/asp/pl_start.asp?typ=14&sub=321&subsub=480&menu=356&strona=1',
  },
  {
    title: 'Niemczówka',
    distance: '8,7km',
    image: NiemczowkaImage,
    link: 'https://niemczowka.pl/',
  },
  {
    title: 'GEONATURA Kielce',
    distance: '23,3km',
    image: GeonaturaImage,
    link: 'https://centrum-geoedukacji.pl/pl/',
  },
  {
    title: 'Anima Libera GUIDO',
    distance: '6,3km',
    image: AnimaLiberaImage,
    link: 'https://animalibera.pl/',
  },
  {
    title: 'UFO',
    distance: '20,7km',
    image: UFOImage,
    link: 'https://dworzec.kielce.pl/index.php',
  },
  {
    title: 'Miasteczko DAKAR',
    distance: '31,8km',
    image: DakarTownImage,
    link: 'https://miasteczkodakar.pl/',
  },
  {
    title: 'Ogród Botaniczny',
    distance: '21,7km',
    image: BotanicGardenImage,
    link: 'https://geonatura-kielce.pl/ogrodbotaniczny/pl/',
  },
  {
    title: 'Zamek Rycerski w Sobkowie',
    distance: '12,9km',
    image: SobkowCastleImage,
    link: 'https://www.zameksobkow.eu/',
  },
  {
    title: 'Agropark Dworek Pod Lipą',
    distance: '21,2km',
    image: LipaManorImage,
    link: 'https://www.agropark.com.pl/',
  },
  {
    title: 'Ostoja Czarownic',
    distance: '5,9km',
    image: WitchHavenImage,
    link: 'https://ostojaczarownic.pl/',
  },
  {
    title: 'Stary Młyn w Wolicy',
    distance: '1,9km',
    image: MillImage,
    link: 'https://goo.gl/maps/fnSyGK3hZRKS4BNMA',
  },
  {
    title: 'Muzeum Garncarstwa w Chałupkach',
    distance: '11,5km',
    image: PotteryCenterImage,
    link: 'https://www.morawica.pl/asp/pl_start.asp?typ=14&sub=125&menu=131&strona=1',
  },
  {
    title: 'Europejskie Centrum Edukacji Geologicznej',
    distance: '9,3km',
    image: GeoCenterImage,
    link: 'https://www.eceg.uw.edu.pl/',
  },
];

export default NEARBY_DATA;
